In [1]:
# Theory nQuestion 

In [2]:
# Question 1 )  What is a Convolutional Neural Network (CNN), and why is it used for image processing?

# A CNN is a type of deep learning model specialized for grid-like data, such as images. It automatically and adaptively learns spatial hierarchies of features through convolutional layers, making it ideal for image recognition, classification, and detection tasks.




# Question 2 )  What are the key components of a CNN architecture?

# Input Layer – Image data (height × width × channels)

# Convolutional Layers – Extract features

# Activation Functions (ReLU) – Introduce non-linearity

# Pooling Layers – Reduce dimensionality

# Fully Connected Layers – Perform classification

# Output Layer – Produces final prediction (e.g., class probabilities)




# Question 3)  What is the role of the convolutional layer in CNNs?

# It applies a set of filters (kernels) that slide over the input image to extract features like edges, corners, textures, etc., producing feature maps.



#Question 4️)  What is a filter (kernel) in CNNs?

# A small matrix (e.g., 3×3 or 5×5) of trainable weights that performs element-wise multiplication and summation with the input region, helping the network learn patterns.




# Question 5️)  What is pooling in CNNs, and why is it important?

# Pooling reduces the spatial dimensions of feature maps (height and width), retaining the most important information. It:

# Reduces computational cost

# Prevents overfitting

# Introduces spatial invariance




# Question 6️)  What are the common types of pooling used in CNNs?

# Max Pooling – Selects the maximum value from a region

# Average Pooling – Computes the average value from a region

# Global Average Pooling – Reduces the entire feature map to a single value per channel




# Question 7️) How does the backpropagation algorithm work in CNNs?


# Backpropagation in CNNs computes the gradient of the loss function w.r.t. each weight using the chain rule, then updates the weights using gradient descent. It handles convolutional and fully connected layers differently due to weight sharing in convolutions.



# Question 8)  What is the role of activation functions in CNNs?

# They introduce non-linearity so that the model can learn complex functions. Common activation functions:

# ReLU – f(x) = max(0, x)

# Sigmoid – Good for binary output

# Softmax – For multi-class classification (in the output layer)



# Question 9️)  What is the concept of receptive fields in CNNs?
# The receptive field is the region in the input image that a particular neuron in a feature map "sees." As you move deeper in the network, receptive fields grow larger, capturing more global context.



# Question 10)  Explain the concept of tensor space in CNNs?

# A tensor is a multi-dimensional array (generalized matrix). In CNNs, data flows through as:

# 3D tensor: (Height × Width × Channels) for images

# 4D tensor: (Batch × Height × Width × Channels) during training

# This structure helps process and compute over batches efficiently.



# Question 11)  What is LeNet-5, and how does it contribute to the development of CNNs?

# Developed by Yann LeCun in the 1990s for handwritten digit recognition (MNIST).

# Introduced convolution + pooling + fully connected layers.

# One of the earliest CNNs, forming the foundation for modern architectures.



# Question 12)  What is AlexNet, and why was it a breakthrough in deep learning?

# Won ImageNet 2012 challenge with huge margin.

# Used ReLU, dropout, data augmentation, and GPU training.

# Deep network (8 layers) — brought CNNs to mainstream in computer vision.



#  Question13)  What is VGGNet, and how does it differ from AlexNet?


# Uses only 3×3 convolution filters and very deep architecture (16 or 19 layers).

# Simpler, more uniform design compared to AlexNet.

# Better performance with deeper yet cleaner structure.




# Question 14)   What is GoogLeNet, and what is its main innovation?

# Introduced Inception Modules — multiple filter sizes in one layer.

# Reduced parameters using 1×1 convolutions (bottleneck layers).

# Won ImageNet 2014. Very efficient and deep.




# Question 15)  What is ResNet, and what problem does it solve?


# Introduced residual connections (skip connections).

# Solves vanishing gradient problem in very deep networks.

# Enabled training of ultra-deep networks (e.g., 152 layers).




#  Question 16)  What is DenseNet, and how does it differ from ResNet?

# In DenseNet, each layer is connected to all subsequent layers.

# Promotes feature reuse, reduces parameters.

# Unlike ResNet, which adds output of layers, DenseNet concatenates them.




# Questioin 17)   What are the main steps involved in training a CNN from scratch?


# Prepare dataset – Images + labels, resize/normalize, split into train/val/test

# Define model architecture – Layers, activations, optimizer

# Forward pass – Compute predictions

# Loss computation – Measure error using a loss function

# Backpropagation – Calculate gradients

# Update weights – Using an optimizer like SGD or Adam

# Repeat (epochs) – Until model converges

# Evaluate – Accuracy, loss, confusion matrix

# Deploy – Save and use the trained model

# If you want this in a PDF or formatted notes file, let me kn

PRACTICAL 

In [3]:
# Question 1)  Implement a basic convolution operation using a filter and a 5x5 image (matrix) 
import numpy as np
from scipy.signal import convolve2d

image = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 2],
    [7, 8, 9, 0, 1],
    [1, 3, 2, 2, 3],
    [0, 1, 2, 3, 4]
])

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

convolved = convolve2d(image, kernel, mode='valid')
print("Convolved Output:\n", convolved)


Convolved Output:
 [[  6 -14 -14]
 [  5 -13 -11]
 [  5  -7  -5]]


In [4]:
# Question 2)  Implement max pooling on a 4x4 feature map with a 2x2 window

import numpy as np
from skimage.measure import block_reduce

feature_map = np.array([
    [1, 3, 2, 1],
    [4, 6, 5, 2],
    [7, 2, 8, 3],
    [1, 0, 6, 4]
])

pooled = block_reduce(feature_map, block_size=(2, 2), func=np.max)
print("Max Pooled Output:\n", pooled)


Max Pooled Output:
 [[6 5]
 [7 8]]


In [6]:
# Question 3) Implement the ReLU activation function on a feature map

feature_map = np.array([
    [-1, 2],
    [3, -4]
])

relu_activated = np.maximum(0, feature_map)
print("ReLU Output:\n", relu_activated)


ReLU Output:
 [[0 2]
 [3 0]]


In [9]:
# Question 4 ) Create a simple CNN model with one convolutional layer and a fully connected layer, using random data 

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(8, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.summary()


C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 8)      │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 5408)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │        54,090 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54,170 (211.60 KB)

 Trainable params: 54,170 (211.60 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
# Question 5)  Generate a synthetic dataset using random noise and train a simple CNN model on it


import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense

X = np.random.rand(100, 28, 28, 1)
y = tf.keras.utils.to_categorical(np.random.randint(0, 10, 100), 10)

model = Sequential([
    Conv2D(16, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    Flatten(),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=5, batch_size=16)



C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.0416 - loss: 2.5494
Epoch 2/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2217 - loss: 2.2249
Epoch 3/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 101ms/step - accuracy: 0.4682 - loss: 1.8596
Epoch 4/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6607 - loss: 1.6844
Epoch 5/5
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9784 - loss: 1.2780 


In [12]:
# Question 6) Create a simple CNN using Keras with one convolution layer and a max-pooling layer

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2))
])

model.summary()



C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_2 (Conv2D)               │ (None, 26, 26, 16)     │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 16)     │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 160 (640.00 B)

 Trainable params: 160 (640.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
# Question 7 ) Write a code to add a fully connected layer after the convolution and max-pooling layers in a CNN

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])



C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [14]:
# Question 8 ) Write a code to add  batch normalization to a simple CNN modeL. 

from tensorflow.keras.layers import BatchNormalization

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    BatchNormalization(),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])



C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [15]:
# Question 9 )  Write a code to add dropout regularization to a simple CNN model 

from tensorflow.keras.layers import Dropout

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    Dropout(0.5),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])


C:\Users\Hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [16]:
# Questin 10)  Write a code to print the architecture of the VGG16 model in Keras. 


from tensorflow.keras.applications import VGG16

model = VGG16()
model.summary()


553467096/553467096 ━━━━━━━━━━━━━━━━━━━━ 86s 0us/step


Model: "vgg16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_6 (InputLayer)      │ (None, 224, 224, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv1 (Conv2D)           │ (None, 224, 224, 64)   │         1,792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_conv2 (Conv2D)           │ (None, 224, 224, 64)   │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block1_pool (MaxPooling2D)      │ (None, 112, 112, 64)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv1 (Conv2D)           │ (None, 112, 112, 128)  │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_conv2 (Conv2D)           │ (None, 112, 112, 128)  │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block2_pool (MaxPooling2D)      │ (None, 56, 56, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv1 (Conv2D)           │ (None, 56, 56, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv2 (Conv2D)           │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_conv3 (Conv2D)           │ (None, 56, 56, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block3_pool (MaxPooling2D)      │ (None, 28, 28, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv1 (Conv2D)           │ (None, 28, 28, 512)    │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv2 (Conv2D)           │ (None, 28, 28, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_conv3 (Conv2D)           │ (None, 28, 28, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block4_pool (MaxPooling2D)      │ (None, 14, 14, 512)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv1 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv2 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_conv3 (Conv2D)           │ (None, 14, 14, 512)    │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ block5_pool (MaxPooling2D)      │ (None, 7, 7, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc1 (Dense)                     │ (None, 4096)           │   102,764,544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ fc2 (Dense)                     │ (None, 4096)           │    16,781,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ predictions (Dense)             │ (None, 1000)           │     4,097,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 138,357,544 (527.79 MB)

 Trainable params: 138,357,544 (527.79 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# # Question 11 ) Write a code to plot the accuracy and loss graphs after training a CNN model. 

# import matplotlib.pyplot as plt

# # After model.fit()
# history = model.fit(X, y, epochs=5, validation_split=0.2)

# plt.plot(history.history['accuracy'], label='Train Accuracy')
# plt.plot(history.history['val_accuracy'], label='Val Accuracy')
# plt.plot(history.history['loss'], label='Train Loss')
# plt.plot(history.history['val_loss'], label='Val Loss')
# plt.xlabel("Epoch")
# plt.ylabel("Accuracy/Loss")
# plt.legend()
# plt.title("Training and Validation Accuracy/Loss")
# plt.show()

 

ValueError: You must call `compile()` before using the model.

In [18]:
# Question 12)  Write a code to print the architecture of the ResNet50 model in Keras*

from tensorflow.keras.applications import ResNet50

model = ResNet50()
model.summary()



Model: "resnet50"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_7       │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_pad           │ (None, 230, 230,  │          0 │ input_layer_7[0]… │
│ (ZeroPadding2D)     │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_conv (Conv2D) │ (None, 112, 112,  │      9,472 │ conv1_pad[0][0]   │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_bn            │ (None, 112, 112,  │        256 │ conv1_conv[0][0]  │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1_relu          │ (None, 112, 112,  │          0 │ conv1_bn[0][0]    │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pool1_pad           │ (None, 114, 114,  │          0 │ conv1_relu[0][0]  │
│ (ZeroPadding2D)     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ pool1_pool          │ (None, 56, 56,    │          0 │ pool1_pad[0][0]   │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_1_conv │ (None, 56, 56,    │      4,160 │ pool1_pool[0][0]  │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_1_bn   │ (None, 56, 56,    │        256 │ conv2_block1_1_c… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_1_relu │ (None, 56, 56,    │          0 │ conv2_block1_1_b… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_conv │ (None, 56, 56,    │     36,928 │ conv2_block1_1_r… │
│ (Conv2D)            │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_bn   │ (None, 56, 56,    │        256 │ conv2_block1_2_c… │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_2_relu │ (None, 56, 56,    │          0 │ conv2_block1_2_b… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_0_conv │ (None, 56, 56,    │     16,640 │ pool1_pool[0][0]  │
│ (Conv2D)            │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_3_conv │ (None, 56, 56,    │     16,640 │ conv2_block1_2_r… │
│ (Conv2D)            │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_0_bn   │ (None, 56, 56,    │      1,024 │ conv2_block1_0_c… │
│ (BatchNormalizatio… │ 256)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2_block1_3_bn   │ (None, 56, 56,    │      1,024 │ conv2_block1_3_c

 Total params: 25,636,712 (97.80 MB)

 Trainable params: 25,583,592 (97.59 MB)

 Non-trainable params: 53,120 (207.50 KB)

In [20]:
# # Question 13)  Write a code to train a basic CNN model and print the training loss and accuracy after each epoch?

# model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# history = model.fit(X, y, epochs=5, verbose=1)
